language: python
sudo: false
python:
  - '2.7'
  - '3.5'
  - '3.6'
env:
  global:
    - GITHUB_REPO=biosustain/optlang
    - secure: PBcwrLg4ZwVi9Gw25Q2adNd0uK+NCqFSiYl+ZuumkEXs4NQBbSXVd719wrWKUFdIqBy+h9ETo4Vsz/QsTZzI2mSG4zqTkm+oUxMW1tJxYEeKZvCo7GfZ883VlKFgdqvh6iouEvHSjfGbwc5cUp98CbjgI5ni01vGpDQh2hgokkI=
    - OPTLANG_USE_SYMENGINE=False
    - OPTLANG_USE_SYMENGINE=True
    - SYMPY_USE_CACHE=no

matrix:
  fast_finish: true
git:
  depth: 2
cache:
  pip: true

before_install:
  - if [[ "$TRAVIS_PYTHON_VERSION" != "3.5" ]]; then
      bash ./.travis/install_cplex.sh;
    fi
install:
  - pip install --upgrade pip setuptools wheel tox tox-travis
script:
  - tox -- --cov=optlang --cov-report xml --cov-report term
  - bash <(curl -s https://codecov.io/bash)

stages:
- test
- name: deploy
  if: tag IS present

jobs:
  include:
  - stage: deploy
    before_install: skip
    install: skip
    script:
    - echo "Deploying optlang."
    deploy:
    - provider: pypi
      skip_cleanup: true
      user: Nikolaus.Sonnenschein
      password:
        secure: Gn23MUvzP1DPJXxRXUOXGBJjyMamawxey5ByrOd+JT90roljHKSk8v1wdBMH7+s1DB/ygUJqB2Zy0cBC3mr0waY6HmxKpXhddgzQzG56Eua/npTxpz58Y8xfSYF+5QqS3gcyBrYEXmeHWuEURERy0b7uYKMx/QcHAHYhTaVy4zE=
      on:
        tags: true
        repo: $GITHUB_REPO
    - provider: releases
      skip_cleanup: true
      api_key:
        secure: u4aJv+5YoH3gjJpyiVoq33SqKIUtx8LWPp15pIh8hKHmUgJNyjGm7ELXOeczfQ5W7ZpnWj+ogewaes2oA0NLxBB1/MBPL7kr77hmzp+XhZomh73DzFKegbpBTgqpioBRxvPlq3HYNIWqrLkeg/HYlBW1WM6mKifFUwqbIaL+++4=
      body: "Please see https://github.com/${GITHUB_REPO}/blob/${TRAVIS_TAG}/CHANGELOG.rst for the full release notes."
      on:
        tags: true
        repo: $GITHUB_REPO

notifications:
  email: false
  slack:
    secure: s8Dj0MFreNwZ3Zhb0+5yJiHPL33JsxLjmoRo8f0ohLdD15L//E4VjkCsYkNEcLzid6HarEL/1JSmzAuGl40fCdLqTAoDRy01shT1zmfWQPXQlaALh5f8ExBAlyDHxKhd/B2SytYu6uhe0WOuxu/oo4c33a7pKhuV1piNcevPZew=
    on_success: change
    on_failure: change
    on_pull_requests: false
