language: python
python:
- '2.7'
- '3.4'
before_install:
- sudo apt-get install libglpk-dev swig python-numpy glpk-utils pandoc
- export SYMPY_USE_CACHE=no
install:
- pip install coveralls nose nose-progressive rednose coverage docutils
- pip install -r requirements.txt
- pip install pypandoc  # needed for proper pypi deployment
- python setup.py install
script: python setup.py nosetests
after_success:
- coveralls
deploy:
  provider: pypi
  user: Nikolaus.Sonnenschein
  password:
    secure: Gn23MUvzP1DPJXxRXUOXGBJjyMamawxey5ByrOd+JT90roljHKSk8v1wdBMH7+s1DB/ygUJqB2Zy0cBC3mr0waY6HmxKpXhddgzQzG56Eua/npTxpz58Y8xfSYF+5QqS3gcyBrYEXmeHWuEURERy0b7uYKMx/QcHAHYhTaVy4zE=
  on:
    tags: true
    repo: biosustain/optlang
