language: python
before_install:
  - sudo apt-get install libglpk-dev
  - cd /home/travis
  - wget http://www.dcc.fc.up.pt/~jpp/code/python-glpk/python-glpk_0.4.45.orig.tar.gz
  - tar xzf python-glpk-0.4.43.tar.gz
  - cd python-glpk-0.4.43
  - make install
install:
  - pip install -r requirements.txt
# # command to run tests
script: nosetests .
